### ISSUE TITLE
Current master installation fails on Mac OS X 10.11

### ISSUE THREAD

**Issue by felixveysseyre** [Kitware/paraviewweb#312]
Hello,

I am trying to install the latest master version of ParaViewWeb project.
I am following the instruction given in this file: https://github.com/Kitware/paraviewweb/blob/master/README.md

When running `npm run build`, I got the following error:
```
> paraviewweb@0.0.0-semantically-release build /Users/felixveysseyre/Projects/ParaViewWebTesting
> npm run bin:fix-autobahn && webpack --progress --colors


> paraviewweb@0.0.0-semantically-release bin:fix-autobahn /Users/felixveysseyre/Projects/ParaViewWebTesting
> node ./tools/fix-autobahn/patch-autobahn-0.9.6-cli.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/felixveysseyre/Projects/ParaViewWebTesting/webpack.config.js:41:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Darwin 15.2.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "run" "build"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! paraviewweb@0.0.0-semantically-release build: `npm run bin:fix-autobahn && webpack --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the paraviewweb@0.0.0-semantically-release build script 'npm run bin:fix-autobahn && webpack --progress --colors'.
npm ERR! This is most likely a problem with the paraviewweb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bin:fix-autobahn && webpack --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs paraviewweb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls paraviewweb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/felixveysseyre/Projects/ParaViewWebTesting/npm-debug.log
```

It seems like a Webpack error, but since I do not have any knowledge on this technology I am creating this issue.

Thanks for your help !

**Comment by jourdain** [comment]
Did you run `npm install` first?

I may have forgot to mention it in the documentation.

But if you did that would mean you have an old version of npm < 3.

If not, please share your node and npm version.

Thanks,

Seb

**Comment by felixveysseyre** [comment]
Thanks for your answer Sebastien !

I did run `npm install` before.

My current version of `npm` and `node` are listed in the error message:
```
npm ERR! node v4.6.1
npm ERR! npm  v2.15.11
```

Should I upgrade my `npm` to `npm3` before run ParaViewWeb installation ?

Thanks again !

**Comment by jourdain** [comment]
Yes npm 3 is a requirement

**Comment by felixveysseyre** [comment]
I updated my `npm` to v3.10.9 and I still get the same error:
```
hydra:ParaViewWebTesting npm run build

> paraviewweb@0.0.0-semantically-release build /Users/felixveysseyre/Projects/ParaViewWebTesting
> npm run bin:fix-autobahn && webpack --progress --colors


> paraviewweb@0.0.0-semantically-release bin:fix-autobahn /Users/felixveysseyre/Projects/ParaViewWebTesting
> node ./tools/fix-autobahn/patch-autobahn-0.9.6-cli.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/felixveysseyre/Projects/ParaViewWebTesting/webpack.config.js:41:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/felixveysseyre/.nvm/versions/node/v6.9.2/bin/node" "/Users/felixveysseyre/.nvm/versions/node/v6.9.2/bin/npm" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! paraviewweb@0.0.0-semantically-release build: `npm run bin:fix-autobahn && webpack --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the paraviewweb@0.0.0-semantically-release build script 'npm run bin:fix-autobahn && webpack --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the paraviewweb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bin:fix-autobahn && webpack --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs paraviewweb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls paraviewweb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/felixveysseyre/Projects/ParaViewWebTesting/npm-debug.log
```

Here are my current versions:
```
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
```

**Comment by jourdain** [comment]
```
$ rm -rf node_modules
$ npm install
$ npm run build
```

The issue is related to the structure of your node_modules.

**Comment by felixveysseyre** [comment]
It fixed the issue.

Thanks @jourdain !
