### ISSUE TITLE
Issues with webpack

### ISSUE THREAD

**Issue by shaolun-Ryan** [Kitware/paraviewweb#505]
when i first `npm start` the code. The errer is shown as follows:
```shell
Module build failed (from ./node_modules/_css-loader@3.2.0@css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
    at validate (E:\pvw0\node_modules\_schema-utils@2.5.0@schema-utils\dist\validate.js:50:11)
    at Object.loader (E:\pvw0\node_modules\_css-loader@3.2.0@css-loader\dist\index.js:34:28)
 @ ./node_modules/_paraviewweb@3.2.12@paraviewweb/style/ComponentNative/Composite.mcss 1:14-174
 @ ./node_modules/_paraviewweb@3.2.12@paraviewweb/src/Component/Native/Composite/index.js
 @ ./node_modules/_babel-loader@8.0.6@babel-loader/lib??ref--18-0!./src/index.js
 @ ./src/index.js-exposed
```
It shows something goes wrong when packing.
And then change the code like this, the pkg will be compiled successfully.
**Previous:**
```json
use: [
      { loader: 'style-loader' },
      {
        loader: 'css-loader',
        options: {
          localIdentName: '[name]-[local]_[sha512:hash:base32:5]',
          modules: true,
        },
      },
      {
        loader: 'postcss-loader',
        options: {
          plugins: () => [autoprefixerPlugin],
        },
      },
    ],
```
**Now**
```json
use: [
      { loader: 'style-loader' },
      {
        loader: 'css-loader',
        options: {
          modules:{
            localIdentName: '[name]-[local]_[sha512:hash:base32:5]',
          },
          modules: true,
        },
      },
      {
        loader: 'postcss-loader',
        options: {
          plugins: () => [autoprefixerPlugin],
        },
      },
    ],
```

**Comment by jourdain** [comment]
Thanks for sharing the solution, but I'm not sure where you ran `npm start` as we don't have such entry available.

**Comment by shaolun-Ryan** [comment]
Hi there！
This is the original text below at&nbsp;https://kitware.github.io/paraviewweb/docs/setup.html


“Run
To build your application you can run npm run build and to test/debug it npm start while opening http://localhost:9999.”


I just followed the cmd at the DOC document.
I hope i made everything right throughout the building process.
Thx！



发自我的iPhone


------------------ Original ------------------

**Comment by jourdain** [comment]
I see, indeed for running pvw example we do provide a "start" command. Thanks for refreshing my memory. ;-)

**Comment by shaolun-Ryan** [comment]
Hah！I didn't do anything actually:)
So the error info i provided is an error indeed or it's just a mistake i made.
(By the way, I'm afraid it is an update of webpack which u used for bundling the scripts of pvw.)
Thx！



发自我的iPhone


------------------ Original ------------------
