### ISSUE TITLE
cann'nt run 

### ISSUE THREAD

**Issue by DavidMGT** [Kitware/paraviewweb#545]
### High-level description
when I type "npm run build" or "npm run test",it doesnt work

### Detailed behavior
    at BulkUpdateDecorator.hashFactory (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:946:10)
    at /Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:755:11)
    at /Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
hanglok@hanglokdeMacBook-Air paraviewweb-master % clear

hanglok@hanglokdeMacBook-Air paraviewweb-master % npm run build

> paraviewweb@0.0.0-semantically-release build
> webpack --progress --mode development --devtool source-map

10% building 0/1 entries 1/1 dependencies 0/1 modulesBrowserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at BulkUpdateDecorator.hashFactory (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack-sources/lib/OriginalSource.js:138:8)
    at NormalModule._initBuildHash (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:946:10)
    at /Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:755:11)
    at /Users/hanglok/work/web/ParaView/paraviewweb-master/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.0
### Environment
- **paraviewweb**: 
- **OS**: 
- **Browser**:

**Comment by jourdain** [comment]
Duplicate of https://github.com/Kitware/paraviewweb/issues/544 and https://github.com/Kitware/paraviewweb/issues/535.

The main issue is that paraviewweb was getting developed till Node v8. Now we are in v20. So the build system needs to be re-worked if you really want to build it again.

But why do you aim to use that web library when all you need is part of VTK/ParaView and vtk.js or even better [trame](https://kitware.github.io/trame/)?
